/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": null,
        "tagline": null,
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-509b31c6",
      "path": "/"
    },
    {
      "frontmatter": {},
      "regularPath": "/components/button.html",
      "relativePath": "components/button.md",
      "key": "v-09e7d5eb",
      "path": "/components/button.html"
    },
    {
      "frontmatter": {},
      "regularPath": "/components/ChangeLog.html",
      "relativePath": "components/ChangeLog.md",
      "key": "v-7a6c53fe",
      "path": "/components/ChangeLog.html"
    },
    {
      "title": "安装",
      "frontmatter": {},
      "regularPath": "/components/guide/installation.html",
      "relativePath": "components/guide/installation.md",
      "key": "v-477fd9f8",
      "path": "/components/guide/installation.html",
      "headers": [
        {
          "level": 3,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 3,
          "title": "npm 安装",
          "slug": "npm-安装"
        },
        {
          "level": 3,
          "title": "CDN",
          "slug": "cdn"
        },
        {
          "level": 3,
          "title": "Hello world",
          "slug": "hello-world"
        }
      ]
    },
    {
      "title": "禁用状态",
      "frontmatter": {},
      "regularPath": "/components/input.html",
      "relativePath": "components/input.md",
      "key": "v-2a924a15",
      "path": "/components/input.html",
      "headers": [
        {
          "level": 3,
          "title": "禁用状态",
          "slug": "禁用状态"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/components/guide/quickstart.html",
      "relativePath": "components/guide/quickstart.md",
      "key": "v-46a83fd8",
      "path": "/components/guide/quickstart.html"
    }
  ],
  "themeConfig": {
    "logo": "/logo.svg",
    "algolia": {
      "apiKey": "<API_KEY>",
      "indexName": "<INDEX_NAME>"
    },
    "nav": [
      {
        "text": "指南",
        "link": "/"
      },
      {
        "text": "组件",
        "link": "/components/ChangeLog.html"
      },
      {
        "text": "字体",
        "link": "https://google.com"
      },
      {
        "text": "资源",
        "link": "https://baidu.com"
      }
    ],
    "sidebar": [
      {
        "title": "更新日志",
        "path": "/components/ChangeLog.html",
        "collapsable": false,
        "sidebarDepth": 0
      },
      {
        "title": "开发指南",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          {
            "title": "安装",
            "path": "/components/guide/installation",
            "collapsable": false,
            "sidebarDepth": 0
          },
          {
            "title": "快速上手",
            "path": "/components/guide/quickstart",
            "collapsable": false,
            "sidebarDepth": 0
          }
        ]
      },
      {
        "title": "组件",
        "children": [
          {
            "title": "input",
            "path": "/components/input",
            "collapsable": false,
            "sidebarDepth": 0
          }
        ],
        "initialOpenGroupIndex": -1
      }
    ]
  }
}